### ISSUE TITLE
[Предложение] Добавление ивентов в мирный режим

### ISSUE THREAD

**Issue by Kinar7** [space-sunrise/lust-station#110]
**Ваш запрос функции связан с проблемой/ошибкой? Опишите, пожалуйста.**
Мирный Режим слишком скучный и ивентов там почти нет.

**Опишите желаемое**
Добавить безопасные ивенты, по типу появления Мышей, Улиток, Тараканов. Йонный шторм. Подарки от корпорации. Бюрократические Ошибки.

**Дополнительный контекст**

**Comment by kanopus952** [comment]
Как по мне это реально нужно

**Comment by VigersRay** [comment]
Бредовая предложка.
Существует Экстра - нет явных антагов но есть события.
Тот же мирный - нету ни антагов, ни событий.
Зачем превращать мирный в экстру?
Если не нравится что часто мирный на сервере то это другая предложка.

**Comment by kanopus952** [comment]
Я снова же поддержу. Если мирный будет содержать небольшие безобидные события, это не навредит игровому опыту игроков, а сделает его чуть приятнее. В экстре же есть мидраунд антаги, плюс там есть те же агенты если выпадет событие на спящих агентов.
