### ISSUE TITLE
[Предложение] Система уровней ерп Боргам

### ISSUE THREAD

**Issue by Kinar7** [space-sunrise/lust-station#112]
**Ваш запрос функции связан с проблемой/ошибкой? Опишите, пожалуйста.**
Борги не могут выбирать уровни ерп, что может привести к проблемам. На пример человек не хочет что бы его ебали за борга, но по логике второго закона должен повиноваться приказам сотрудников станции. 

**Опишите желаемое**
Добавить отображение уровней ерп боргам

**Дополнительный контекст**

**Comment by kanopus952** [comment]
Я лучше сделаю выбор между обычными боргами и этими дылдами

**Comment by Kinar7** [comment]
> Я лучше сделаю выбор между обычными боргами и этими дылдами

Так даже лучше будет

**Comment by VigersRay** [comment]
> **Ваш запрос функции связан с проблемой/ошибкой? Опишите, пожалуйста.** Борги не могут выбирать уровни ерп, что может привести к проблемам. На пример человек не хочет что бы его ебали за борга, но по логике второго закона должен повиноваться приказам сотрудников станции.
> 
> **Опишите желаемое** Добавить отображение уровней ерп боргам
> 
> **Дополнительный контекст**

Больше не может повиноваться, это нарушает законы "НТ стандарт"
